### PR TITLE
Add instances for Lift[F, F] and Provide[Kleisli[F, R, *], Kleisli[F, R, *], R]

### PR DESCRIPTION
**Pull request by bplommer**
Needed for https://github.com/trace4cats/trace4cats-http4s/pull/21

### CODE REVIEW

**Comment by janstenpickle** [comment]
Thanks for this @bplommer, it looks like it's failing on the build unfortunately.

**Comment by catostrophe** [comment]
I'll look at this on weekend.

**Comment by bplommer** [comment]
Looks like I forgot about Scala 3 - I'll fix it up later.

**Comment by catostrophe** [comment]
Btw, do the law checks pass  for these instances? As for me, a `Provide[F, G, R]` instance is evidence that `forall A. R => F[A] == G[A]`.

Also, I would like to look at the use-case where it's needed. I saw the PR in the `http4s` module. It is said that the client may be already lifted. In general, for me it's an antipattern to lift an F-service in a contextual effect beyond the scope where you can provide and apply the context. Doing so requires the context type to have some magic `empty` value that is provided in the outer scope, which is not always possible. That's why we have two separate effects in our implementations. What if there was no empty Span? What if Span was some opaque structure that can be instantiated only at the edge where tracing starts?

I may be absolutely wrong though. So I would like to look at the use-cases and think if it may be done in another way.

**Comment by janstenpickle** [comment]
@bplommer I do agree with @catostrophe in not understanding the need for this. Would you mind explaining the use case?

**Comment by bplommer** [comment]
Sorry, I'll get back to you on this soon!

**Comment by catostrophe** [comment]
Closing this. It may be reopened if the motivation for this change is provided.

**Pull request closed without merging**
